version: '3.3'

services:
  db:
    image: mysql:5.7
    container_name: bookdb_mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD:  ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD:  ${DB_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - ./Database:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d